# Generated by Django 4.0.1 on 2022-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reprint',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='reprint',
            name='date',
            field=models.DateField(verbose_name='Reprint Date'),
        ),
    ]
